### ISSUE TITLE
HTTP methods other than GET

### ISSUE THREAD

**Issue by keith-bennett-gbg** [rduldulao/tornado-swirl#12]
Hi @rduldulao 

This library seems pretty spiffy. Thanks for putting the effort into it.

I followed the [tutorial](https://github.com/rduldulao/tornado-swirl/blob/master/TUTORIAL.md) to write up something quick for GET and it looks good. It's not as feature-rich as OpenAPI 3.0 yet, but it certainly looks like good work so far. I went to write something for HEAD and noticed it didn't show up in the documentation spec at http://localhost:8888/swagger/spec.html.

Tornado supports a bunch of different HTTP methods and even lets the developer specify custom HTTP methods too. It looks like you're going that route with [`swirl.settings.default_settings['enabled_methods']`](https://github.com/rduldulao/tornado-swirl/blob/3b64ad5c2114784e04a2cfc094205e6e7d77b743/tornado_swirl/settings.py#L23) and configurable when calling [`swirl.describe()`](https://github.com/rduldulao/tornado-swirl/blob/3b64ad5c2114784e04a2cfc094205e6e7d77b743/tornado_swirl/swagger.py#L48-L52). If so, then I like this approach. But it does not yet look like it's being used anywhere in the library; `grep -nR enabled_methods ./` shows it's only ever set and never referenced.

What are your thoughts on the matter?

Thanks,
@keith-bennett-gbg

**Comment by rduldulao** [comment]
Hi Keith,

I haven't been updating the module lately since it already does what we
want in our API projects.  I will see to this as soon as I have some time
off my day job (which may be later in the afternoon in our timezone), but
yes, I was thinking the allowed methods should be configurable - I will be
considering your suggestion.

rduldulao (Dulds)

**Comment by rduldulao** [comment]
Hi again,  

Please see lates release v_0.1.14

**Comment by keith-bennett-gbg** [comment]
:+1: that's great. Thank you!
