### ISSUE TITLE
How to add multiple handlers

### ISSUE THREAD

**Issue by vvadher** [rduldulao/tornado-swirl#14]
HI @rduldulao 

I tried your sample code and I am trying to use multiple handlers.
Here is my make_app method
`def make_app():
      return Application(api_routes(), autoreload=False)
    # return Application([
    #     (r"/v1/foosh1", SampleHandler1),
    #     (r"/v1/foosh2", SampleHandler2),`
How to use api_routes() to work with multiple handlers?

**Comment by rduldulao** [comment]
Hi,
You just need to use the decorateor @restapi to all the handlers you're gonna include:  i.e.

`
@restapi(url='/v1/foosh1')
class SampleHandler1(RequestHandler):
    . . . 

@restapi(url='/v1/foosh2')
class SampleHandler2(RequestHandler):
   . . .
`

The way we did it in our project though is IF you do not want to use the restapi decorator and use it as a func instead:

`
def swirlify(base_path, path, handler):
    """Convert path, handler"""
    return path, restapi("/" + base_path + path)(handler)`

routes = [
     swirlify("", r"/v1/foosh1", SampleHandler1),
     swirlify("", r"/v1/foosh2", SampleHandler2)
]

app = Application(routes)
