### ISSUE TITLE
websockets docs

### ISSUE THREAD

**Issue by roman-telepathy-ai** [rduldulao/tornado-swirl#15]
hi,

are there any activities to document websockets?

thx, r

**Comment by rduldulao** [comment]
Hi @roman-telepathy-ai .  Sorry for the late reply.  No activities re: websockets at the moment, will try to scope it out if it can be added for our next release.  If you could provide a description of your requirements, that would be great.  Thanks.

**Comment by roman-telepathy-ai** [comment]
@rduldulao no worries, I describe them as kind of REST at the moment. WS docs is complicated topic.

thx!
