### ISSUE TITLE
Add support for API Keys

### ISSUE THREAD

**Issue by jjafuller** [rduldulao/tornado-swirl#19]
I'd like to add support for API Keys as per https://swagger.io/docs/specification/authentication/api-keys/

I'm happy to submit a PR if you can point me in the right direction to add this functionality.

**Comment by rduldulao** [comment]
Hi @jjafuller ,

I am actually looking to adding this next as we have this requirement soon at work.  Will probably add a new documentation header for Authentication (in docparser.py) and then handling the output to swagger spec (views.py - SwaggerApiHandler)

**Comment by rduldulao** [comment]
Hi again,

Please see new release 0.1.16.

Summary -- defining security schemes

`
import tornado_swirl as swirl
from tornado_swirl.openapi import security

scheme = security.APIKey('MY-API-KEY', location="header")

swirl.add_security_scheme('my_api_key', scheme)
`

Documenting on the Endpoint handler

`
class MyHandler(RequestHandler):

    def get(self):
        """Sample endpoint

        Security:
            my_api_key
        """
`

Also see TUTORIAL.md in repo.

Thank you for your feedback and please do not hesitate to message me for any issues.

**Comment by jjafuller** [comment]
Awesome!
