### ISSUE TITLE
Show Schema Properties info

### ISSUE THREAD

**Issue by freydrich** [rduldulao/tornado-swirl#8]
When defining a schema property, we can also put documentation text. This text does not seem to show anywhere in the swagger ui.

Maybe there is a better way to do what I am trying to do, but basically my api returns a "complexe" json response, and I was using the schema to define and explain the response, but the text I put next to the properties does not seem to show anywhere ex.:
```
@schema
class jsonresponse(object):
    """JSON

    Properties:
      epoch (int) -- Description of the epoch property <-- This text does not seem to show anywhere, although I can see the json structure when this schema class is used in an handler response
...
    """
 ```

**Comment by rduldulao** [comment]
Hi freydrich, sorry for the late response, will try to look into this.  Initial Google search indicates this is a Swagger UI (js) problem though.

**Comment by rduldulao** [comment]
Hi again @freydrich, I've pushed v0.1.11 as fix to the above mentioned problem.

**Comment by freydrich** [comment]
Thanks a lot for the quick fix! It works exactly as I was hoping.
The only thing is in version 0.1.12 at least there is now some extra logs/print statement (Detecting: path, Detecting: ...) Not really an issue, but I thought I would let you know.

**Comment by rduldulao** [comment]
Hi, I missed those in my haste.  This is only a side-project you see and most of my time is focused on our company's current sprint items but I do try to fix bugs ASAP.   I  have already removed them on the updated source code but their removal will reflect in the next release.  Thanks.
